Require python3-setuptools
Otherwise it leads to:

>>> import pikepdf
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/pikepdf/__init__.py", line
      19, in <module>
    from ._version import __version__
  File "/usr/lib64/python3.10/site-packages/pikepdf/_version.py", line
      7, in <module>
    from pkg_resources import DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

https://bugzilla.redhat.com/show_bug.cgi?id=2096442